### PR TITLE
Added wrapper to return bls signer without connecting to VG

### LINKED ISSUE #337: Generate BLS keypair without creating deployable wallet

### PR DESCRIPTION
**Pull request by kautukkundan**
## What is this PR doing?
adds method `generateStaticBlsSigner` on BlsWalletWrapper class to generate a signer without connecting to Verification Gateway

## Does this PR resolve or contribute to any issues?
closes #337 

## Checklist
- [x] I have manually tested these changes
- [x] Post a link to the PR in the group chat

## Guidelines
- If your PR is not ready, mark it as a draft
- The `resolve conversation` button is for reviewers, not authors
  - (But add a 'done' comment or similar)

### CODE REVIEW

**Comment by voltrevo** [comment]
I think it would make more sense to simply use `BlsWalletSigner` directly for this.

ie, instead of:

```ts
const wallet = await BlsWalletWrapper.generateStaticBlsSigner(privateKey, provider);
const publicKey = wallet.getPublicKey();
```

you could just write:

```ts
const network = await provider.getNetwork();
const signer = await initBlsWalletSigner({ chainId: network.chainId });
const publicKey = signer.getPublicKey(privateKey);
```

It's a line longer, but even if we went with `generateStaticBlsSigner` I'd also want it to take `chainId` instead of `provider`, since the only reason it's taking a provider is to get the `chainId` inside. Indeed, this is the reason why `initBlsWalletProvider` takes a `chainId` and not a `provider`. So, it's actually 3 lines either way.

Does that make sense to you? Is there another reason to add this that I might be missing?

**Review by voltrevo — CHANGES_REQUESTED** [review]
See comment above

**Comment by kautukkundan** [comment]
>  Is there another reason to add this that I might be missing?

Yeah kinda, I thought it maybe worthwhile to keep the functionality of connecting to the VG afterwards in case the dev wants to but it feels like instantiating another object with the same details is not too difficult anyway. 
Alright, I'll go over it again, might as well close this PR as the suggested method is already implemented.

**Comment by voltrevo** [comment]
Closing as per suggestion (feel free to re-open if I'm mistaken)

**Pull request closed without merging**
